/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package oopLibrary;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


/**
 *oopLibrary project
 * @author jerrynguyen
 * 15 April 2014
 * Last Updated: April 23, 2014
 * Project Members: Nina Ritchie, Jennifer Sanders
 * 
 */

public class Librarian extends javax.swing.JFrame {

    int intTypeCode;
    int intItemCode;
    ImageIcon imgBook1 = new ImageIcon(getClass().getResource("enders.jpg"));
    ImageIcon imgBook2 = new ImageIcon(getClass().getResource("enders.jpg"));
    ImageIcon imgBook3 = new ImageIcon(getClass().getResource("enders.jpg"));
    ImageIcon imgBook4 = new ImageIcon(getClass().getResource("enders.jpg"));
    ImageIcon imgMedia1 = new ImageIcon(getClass().getResource("tangledPoster.jpg"));
    ImageIcon imgMedia2 = new ImageIcon(getClass().getResource("endersmovie.jpg")); 
    ImageIcon imgMedia3 = new ImageIcon(getClass().getResource("laundryServiceShakira.jpg"));
    ImageIcon imgMedia4 = new ImageIcon(getClass().getResource("emeliSandeOurVersionOfEvents.jpg"));
    AudioClip audioFormSound;
    URL urlOpen = Librarian.class.getResource("open.wav");
    URL urlClose = Librarian.class.getResource("close.wav");
    displayForm display = new displayForm();
    AudioVisualMaterial mediaTangled = new AudioVisualMaterial("Walt Disney", "Tangled", "DVD", 14.99, 2010, imgMedia1);
    AudioVisualMaterial mediaEnder = new AudioVisualMaterial("Lionsgate", "Ender's Game", "DVD", 14.99, 2013, imgMedia2);
    AudioVisualMaterial mediaShakira = new AudioVisualMaterial("Shakira", "Laundry Service", "CD", 7.99, 2001, imgMedia3);
    AudioVisualMaterial mediaESande = new AudioVisualMaterial("Emeli Sande", "Our Version of Events", "CD", 11.62, 2012, imgMedia4);
    /**
     * Creates new form Librarian
     */
    public Librarian() {
        initComponents();
        this.getContentPane().setBackground(new Color(149,88,0));
        JOptionPane.showMessageDialog(this,
    "Welcome to the Library!\nPlease start by selecting your category.");
        intTypeCode = 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMediaButtons = new javax.swing.JPanel();
        btnBooks = new javax.swing.JButton();
        btnMedia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlShelf = new javax.swing.JPanel();
        lblItem1 = new javax.swing.JLabel();
        lblItem2 = new javax.swing.JLabel();
        lblItem3 = new javax.swing.JLabel();
        lblItem4 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Library");
        setName("librarianFrame"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlMediaButtons.setBackground(new java.awt.Color(153, 153, 153));

        btnBooks.setText("Books");
        btnBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBooksActionPerformed(evt);
            }
        });

        btnMedia.setText("Other Media");

        btnMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaActionPerformed(evt);
            }
        });

        jLabel1.setText("Category");

        javax.swing.GroupLayout pnlMediaButtonsLayout = new javax.swing.GroupLayout(pnlMediaButtons);
        pnlMediaButtons.setLayout(pnlMediaButtonsLayout);
        pnlMediaButtonsLayout.setHorizontalGroup(
            pnlMediaButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMediaButtonsLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(btnBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(pnlMediaButtonsLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMediaButtonsLayout.setVerticalGroup(
            pnlMediaButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMediaButtonsLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMediaButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlShelf.setBackground(new java.awt.Color(102, 102, 102));
        pnlShelf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopLibrary/notavailable.jpg"))); // NOI18N
        lblItem1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblItem1.setMaximumSize(new java.awt.Dimension(45, 65));
        lblItem1.setMinimumSize(new java.awt.Dimension(45, 65));
        lblItem1.setPreferredSize(new java.awt.Dimension(45, 65));
        lblItem1.setSize(new java.awt.Dimension(45, 65));
        lblItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItem1MouseClicked(evt);
            }
        });

        lblItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopLibrary/notavailable.jpg"))); // NOI18N
        lblItem2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblItem2.setMaximumSize(new java.awt.Dimension(45, 65));
        lblItem2.setMinimumSize(new java.awt.Dimension(45, 65));
        lblItem2.setPreferredSize(new java.awt.Dimension(45, 65));
        lblItem2.setSize(new java.awt.Dimension(45, 65));
        lblItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItem2MouseClicked(evt);
            }
        });

        lblItem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopLibrary/notavailable.jpg"))); // NOI18N
        lblItem3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblItem3.setMaximumSize(new java.awt.Dimension(45, 65));
        lblItem3.setMinimumSize(new java.awt.Dimension(45, 65));
        lblItem3.setPreferredSize(new java.awt.Dimension(45, 65));
        lblItem3.setSize(new java.awt.Dimension(45, 65));
        lblItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItem3MouseClicked(evt);
            }
        });

        lblItem4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopLibrary/notavailable.jpg"))); // NOI18N
        lblItem4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblItem4.setMaximumSize(new java.awt.Dimension(45, 65));
        lblItem4.setMinimumSize(new java.awt.Dimension(45, 65));
        lblItem4.setPreferredSize(new java.awt.Dimension(45, 65));
        lblItem4.setSize(new java.awt.Dimension(45, 65));
        lblItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItem4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlShelfLayout = new javax.swing.GroupLayout(pnlShelf);
        pnlShelf.setLayout(pnlShelfLayout);
        pnlShelfLayout.setHorizontalGroup(
            pnlShelfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlShelfLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlShelfLayout.setVerticalGroup(
            pnlShelfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlShelfLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(pnlShelfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setText("The Library");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlMediaButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlShelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(pnlShelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(pnlMediaButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void displayImages()
    {
        switch(intTypeCode)
        {
            case 1: lblItem1.setIcon(imgBook1);
                    lblItem1.setToolTipText("");
                    lblItem2.setIcon(imgBook1);
                    lblItem2.setToolTipText("");
                    lblItem3.setIcon(imgBook1);
                    lblItem3.setToolTipText("");
                    lblItem4.setIcon(imgBook1);
                    lblItem4.setToolTipText("");
                    audioFormSound = Applet.newAudioClip(urlOpen);
                    break;
            case 2: lblItem1.setIcon(mediaTangled.getCover());
                    lblItem1.setToolTipText(mediaTangled.getAuthorName() + ": " + mediaTangled.getTitleName());
                    lblItem2.setIcon(mediaEnder.getCover());
                    lblItem2.setToolTipText(mediaEnder.getAuthorName() + ": " + mediaEnder.getTitleName());
                    lblItem3.setIcon(mediaShakira.getCover());
                    lblItem3.setToolTipText(mediaShakira.getAuthorName() + ": " + mediaShakira.getTitleName());
                    lblItem4.setIcon(mediaESande.getCover());
                    lblItem4.setToolTipText(mediaESande.getAuthorName() + ": " + mediaESande.getTitleName());
                    audioFormSound = Applet.newAudioClip(urlOpen);
                    break;
        }
    }
    /**
     * Method to display a new frame with the information of the item.
     */
    public void dislayInfoFrame()
    {
        if(intTypeCode != 0)
        {
        JFrame displayFrame = new displayForm();       
        displayFrame.setSize(250,300);
        displayFrame.setResizable(false);
        }
    }
    /**
     * This method will take the value of intTypeCode selected, which is defined by the user selecting
     * books/other media button. By using the switch statement it will change the titles of the labels
     * according to the following category.
     */
    public void setLabelNames()
    {
        switch(intTypeCode)
        {
            case 1: SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                    display.setVisible(true);
                        }
                    });
                    display.lblTitle.setText("Title:");
                    display.lblAuthor.setText("Author:");
                    display.lblType.setText("Book Type:");
                    display.lblPrice.setText("Price:");
                    display.lblPublished.setText("Year Published:");
                    display.lblEdition.setText("Book Edition:");
                    display.lblEdition.setVisible(true); 
                    display.lblNoP.setText("Number of Pages:");
                    display.lblNoP.setVisible(true);
                    display.setTitle("TitleName");
                    break;
            case 2: SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                    display.setVisible(true);
                        }
                    });
                    display.lblTitle.setText("Title:");
                    display.lblAuthor.setText("Artist:");
                    display.lblType.setText("Media Type:");
                    display.lblPrice.setText("Price:");
                    display.lblPublished.setText("Year Published:");
                    display.lblEdition.setVisible(false);//Field is only needed for books
                    display.lblNoP.setVisible(false);//Field is only needed for books
                    display.editionInfo.setVisible(false);
                    display.pagesInfo.setVisible(false);
                    display.setTitle("TitleName");      
                    break;
        }
    }
    public void setDisplayInfo()
    {
        switch(intItemCode)
        {
            case 1: SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                    display.setVisible(true);
                        }
                    });
                    display.titleInfo.setText(mediaTangled.getTitleName());
                    display.lblAuthor.setText("Studio:");
                    display.authorInfo.setText(mediaTangled.getAuthorName());
                    display.typeInfo.setText(mediaTangled.getMediaType());
                    display.priceInfo.setText("$" + Double.toString(mediaTangled.getItemPrice()));
                    display.publishInfo.setText(Integer.toString(mediaTangled.getPublishYear()));
                    display.lblEdition.setText("Book Edition:");
                    display.lblEdition.setVisible(false); 
                    display.lblNoP.setText("Number of Pages:");
                    display.lblNoP.setVisible(false);
                    display.setTitle(mediaTangled.getTitleName());
                    break;
            case 2: SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                    display.setVisible(true);
                        }
                    });
                    display.titleInfo.setText(mediaEnder.getTitleName());
                    display.lblAuthor.setText("Studio:");
                    display.authorInfo.setText(mediaEnder.getAuthorName());
                    display.typeInfo.setText(mediaEnder.getMediaType());
                    display.priceInfo.setText("$" + Double.toString(mediaEnder.getItemPrice()));
                    display.publishInfo.setText(Integer.toString(mediaEnder.getPublishYear()));
                    display.lblEdition.setText("Book Edition:");
                    display.lblEdition.setVisible(false); 
                    display.lblNoP.setText("Number of Pages:");
                    display.lblNoP.setVisible(false);
                    display.setTitle(mediaEnder.getTitleName());      
                    break;
            case 3: SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                    display.setVisible(true);
                        }
                    });
                    display.titleInfo.setText(mediaShakira.getTitleName());
                    display.authorInfo.setText(mediaShakira.getAuthorName());
                    display.typeInfo.setText(mediaShakira.getMediaType());
                    display.priceInfo.setText("$" + Double.toString(mediaShakira.getItemPrice()));
                    display.publishInfo.setText(Integer.toString(mediaShakira.getPublishYear()));
                    display.lblEdition.setText("Book Edition:");
                    display.lblEdition.setVisible(false); 
                    display.lblNoP.setText("Number of Pages:");
                    display.lblNoP.setVisible(false);
                    display.setTitle(mediaShakira.getTitleName());      
                    break;
            case 4: SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                    display.setVisible(true);
                        }
                    });
                    display.titleInfo.setText(mediaESande.getTitleName());
                    display.authorInfo.setText(mediaESande.getAuthorName());
                    display.typeInfo.setText(mediaESande.getMediaType());
                    display.priceInfo.setText("$" + Double.toString(mediaESande.getItemPrice()));
                    display.publishInfo.setText(Integer.toString(mediaESande.getPublishYear()));
                    display.lblEdition.setText("Book Edition:");
                    display.lblEdition.setVisible(false); 
                    display.lblNoP.setText("Number of Pages:");
                    display.lblNoP.setVisible(false);
                    display.setTitle(mediaESande.getTitleName());      
                    break;
        }
        
    }
    
    /**
     * 
     * @param evt mouseclick event for item1
     */
    private void lblItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItem1MouseClicked
        // TODO add your handling code here:
        intItemCode = 1;
        if(intTypeCode != 0)
        {
            dislayInfoFrame();
            setLabelNames();
            audioFormSound.play();
            setDisplayInfo();   
        }
        else
        {
            JOptionPane.showMessageDialog(this,
            "Please start by selecting your category.");
        }
    }//GEN-LAST:event_lblItem1MouseClicked
    /**
     * 
     * @param evt mouseclick event for item2
     */
    private void lblItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItem2MouseClicked
        // TODO add your handling code here:
        intItemCode = 2;
        if(intTypeCode != 0)
        {
            dislayInfoFrame();
            setLabelNames();
            audioFormSound.play();
            setDisplayInfo();
        }
        else
        {
            JOptionPane.showMessageDialog(this,
            "Please start by selecting your category.");
        }
    }//GEN-LAST:event_lblItem2MouseClicked
    /**
     * 
     * @param evt mouseclick event for item3
     */
    private void lblItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItem3MouseClicked
        // TODO add your handling code here:
        intItemCode = 3;
        if(intTypeCode != 0)
        {
            dislayInfoFrame();
            setLabelNames();
            audioFormSound.play();
            setDisplayInfo();
        }
        else
        {
            JOptionPane.showMessageDialog(this,
            "Please start by selecting your category.");
        }
    }//GEN-LAST:event_lblItem3MouseClicked
    /**
     * 
     * @param evt mouseclick event for item4
     */
    private void lblItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItem4MouseClicked
        // TODO add your handling code here:
        intItemCode = 4;
        if(intTypeCode != 0)
        {
            dislayInfoFrame();
            setLabelNames();
            audioFormSound.play();
            setDisplayInfo();
        }
        else
        {
            JOptionPane.showMessageDialog(this,
            "Please start by selecting your category.");
        }
    }//GEN-LAST:event_lblItem4MouseClicked
    /**
     * 
     * @param evt button pressed event for books
     * Will set intTypeCode to 1
     */
    private void btnBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBooksActionPerformed
        // TODO add your handling code here:
        intTypeCode = 1;
        displayImages();       
    }//GEN-LAST:event_btnBooksActionPerformed
    /**
     * 
     * @param evt button pressed event for other media
     * Will set intTypeCode to 2
     */
    private void btnMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaActionPerformed
        // TODO add your handling code here:
        intTypeCode = 2;
        displayImages();       
    }//GEN-LAST:event_btnMediaActionPerformed
    /**
     * button event handler to confirm user from closing.
     * @param evt 
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Warning",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) 
            {
            // yes option
             System.exit(0);   
            } 
            else 
            {
            // no option
            }
    }//GEN-LAST:event_btnExitActionPerformed
    /**
     * event handler to confirm user from closing.
     * @param evt 
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Warning",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) 
            {
                // yes option
                System.exit(0);   
            } 
            else 
            {
            // no option
                setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Librarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooks;
    private javax.swing.JButton btnExit;
    public javax.swing.JButton btnMedia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblItem1;
    private javax.swing.JLabel lblItem2;
    private javax.swing.JLabel lblItem3;
    private javax.swing.JLabel lblItem4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlMediaButtons;
    private javax.swing.JPanel pnlShelf;
    // End of variables declaration//GEN-END:variables
}
